spring.application.name=ex3

server.port=9003
server.servlet.context-path=/

# Logback 설정: 전체 프로젝트의 기본 로그 레벨 설정
# error > warn > info > debug > trace
logging.level.root=info

# 특정 패키지의 기본 로그 레벨 설정
logging.level.net.datasa.ex3=debug

### MySql 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/busan14?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

### Hibernate SQL 설정
# 실행되는 SQL 문 출력 설정
logging.level.org.hibernate.SQL=debug
# SQL에 주입되는 파라미터 값(바인딩 파라미터) 출력 설정
logging.level.org.hibernate.type.descriptor.sql=trace

### JPA 설정
# 데이터베이스 테이블 자동 생성/수정 설정
spring.jpa.hibernate.ddl-auto=update
# MySQL 8 버전 방언(Dialect) 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

### SQL 포맷 및 출력 설정
# System.out 표준 출력 사용 여부 (logger 출력을 위해 false 권장)
spring.jpa.show-sql=false
# Logger를 통한 SQL 문 출력 여부
spring.jpa.properties.hibernate.show_sql=true
# 출력되는 SQL 문을 보기 좋게 정렬(줄바꿈) 여부
spring.jpa.properties.hibernate.format_sql=true