spring.application.name=web1

# 서버가 실행될 포트 번호
# 브라우저에서 http://localhost:9991 로 접속 -> http://localhost:9991/web1
server.port=9991

# 어플리케이션의 기본 경로(Context-Path)를 설정, ' / '는 루트 경로를 의미
server.servlet.context-path=/
# server.servlet.context-path=/web1

## 로그 (5개 레벨이 존재)
# 전체 로그 수준을 INFO로 설정
logging.level.root=info
# 특정 패키지(net.datasa.web1)만 DEBUG 레벨로 설정
logging.level.net.datasa.web1=debug

# 로그 파일 경로와 이름 설정
loggin.file.name=logs/myapp.log
# 로그 파일이 10MB가 되면 자동으로 분할
logging.longback.rollingpolicy.max-file-size=10MB
# 보관할 로그 파일의 최대 일수를 30일로 제한
logging.longback.rollingpolicy.max-history=30