spring.application.name=web4_practice

#소스 코드(HTML, JS, CSS 등 정적 리소스)가 바뀌었을 때, 브라우저를 자동으로 새로고침 해주는 기능
spring.devtools.livereload.enabled=true
#템플릿 수정 후 서버 재시작 없이 바로 적용됨 (단점: 성능은 조금 떨어지지만, 개발 중에는 상관없음)
spring.freemarker.cache=false


## 경로 ######################################################
server.port=9994
server.servlet.context-path=/


## 로그 ######################################################
# 전체를 대상으로 로깅 레벨 지정(Logback)
# error>warn>info>debug>trace
logging.level.root=info
# 특정 패키지를 대상으로 로깅 레벨 지정
logging.level.net.datasa.web4=debug


## 세션 ######################################################
# 세션 만료 시간 설정 - 단위 : s (seconds), m (minutes), h (hours), d (days)
server.servlet.session.timeout=60m


## MySQL ####################################################
# 프로젝트의 바로 하위 디렉토리(build.gradle, .gitignore 파일들과 동일한 위치일 것)에 .env 파일 생성
# 해당 파일에 설정 정보들 입력
# .gitignore 에 .env 작성

# 안먹히면 구성편집에서 Enable EnvFile 체크하고 아래 + 버튼 눌러서 직접 env 파일 가져오기
spring.config.import=optional:file:.env[.properties]

# 데이터베이스 연결 주소 (localhost 및 포트, 데이터베이스명, 접속정보는 본인 환경에 맞게 수정)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


## JPA ######################################################
# JPA 설정
# JPA가 실행하는 SQL을 콘솔에 출력하도록 하는 옵션
spring.jpa.show-sql=true
# DDL(스키마) 자동 생성 전략 - JPA가 DB 스키마를 자동으로 생성·관리할 것인지를 결정하기 위해
#   none        아무 작업도 하지 않음
#   validate    DB와 엔티티가 같은지 확인만 하고, 다르면 에러 발생
#   update      있는 테이블은 유지하되, 변화된 스키마를 자동 업데이트
#   create      서버 실행 시 스키마를 새로 생성(기존 테이블 삭제)
#   create-drop create와 같지만 종료 시 테이블 삭제
spring.jpa.hibernate.ddl-auto=validate
# 데이터베이스마다 SQL 문법이 조금씩 다르기 때문에, MySQL 버전을 사용하겠다는 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# SQL을 콘솔에 포맷팅 해서 출력
spring.jpa.properties.hibernate.format_sql=true
# SQL 바인딩 파라미터 로깅 (Spring Boot 버전에 따라 설정이 다를 수 있어 가장 확실한 2가지 모두 추가)
logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.hibernate.orm.results.mapping=trace

# 특정 IP를 지정하는 것이 아니라, "내 컴퓨터에 할당된 모든 IP 주소로부터 오는 요청을 다 받겠다"는 뜻
# 즉, 내부망(Local), 외부망(Public) 할 것 없이 모든 네트워크 연결을 수락
server.address=0.0.0.0